version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8888:8888
    tty: true
    command: poetry run jupyter lab --allow-root --ip=0.0.0.0
    platform: linux/amd64
